Addition of the attribute name for the subnet in resource_mso_schema_site_vrf_region
CiscoDevNet/terraform-provider-mso pull request #140
Opened 2022-07-07 15:39 UTC by shrsr

2022-07-14 15:45 UTC, xinyuezhao approved these changes
LGTM

2022-07-19 17:01 UTC, anvitha-jain requested changes

2022-07-28 10:31 UTC, shrsr commented on mso/resource_mso_schema_site_vrf_region.go
> +										Optional:     true,
All the attributes in the datasource file except the ones that are Required should be Computed and that doesn't go vice versa with the resource file.
In this case I have set 'name' to optional in resource in order for it to be consistent with the other attribute 'zone'. Let me know if you want me to change both to optional and computed which is possible.

2022-07-28 17:03 UTC, anvitha-jain commented on mso/resource_mso_schema_site_vrf_region.go
> +										Optional:     true,
Adding "computed : true" when "optional: true" is recommended (Unless it disrupts the working part of the existing code.)

2022-08-26 22:05 UTC, anvitha-jain requested changes

2022-08-26 22:05 UTC, anvitha-jain commented on website/docs/d/schema_site_vrf_region.html.markdown
>  * `cidr.primary` - (Optional) primary flag to set above ip as primary for cidr. Only one ip must be set as primary.
ip -> IP

2022-08-26 22:05 UTC, anvitha-jain commented on website/docs/r/schema_site_vrf_region.html.markdown
>  * `cidr.primary` - (Required) Primary flag to set above ip as primary for cidr. Only one ip must be set as primary.
ip -> IP

2022-08-26 22:34 UTC, anvitha-jain approved these changes
LGTM

2022-08-26 22:34 UTC, lhercot approved these changes
LGTM

2022-08-26 22:35 UTC, merged