Add resource and datasource mso_schema_site_l3out
CiscoDevNet/terraform-provider-mso pull request #170
Opened 2023-02-11 13:37 UTC by lhercot

This PR is a part of the phase-2-resources PR

2023-02-14 15:19 UTC, akinross commented on website/docs/r/schema_site_l3out.html.markdown
> +* `schema_id` - (Required) The schema-id where user wants to add L3out.
the L3Out?

2023-02-14 15:20 UTC, akinross commented on website/docs/d/schema_site_l3out.html.markdown
> +* `schema_id` - (Required) The schema-id where L3out is added.
the L3Out?

2023-02-15 09:24 UTC, sajagana requested changes

2023-02-15 09:24 UTC, sajagana commented on examples/schema_site_l3out/main.tf
> +}
Got "Missing required argument" and "Reference to undeclared resource" error messages. While running the example.

2023-03-02 17:07 UTC, anvitha-jain commented on website/docs/d/schema_site_l3out.html.markdown
> +layout: "mso"
Do we need subcategory parameter here?

2023-03-02 17:07 UTC, anvitha-jain commented on website/docs/r/schema_site_l3out.html.markdown
> +layout: "mso"
Do we need subcategory parameter?

2023-03-02 17:07 UTC, anvitha-jain commented on website/docs/r/schema_site_l3out.html.markdown
> +terraform import mso_schema_site_l3out.example {schema_id}/site/{site_id}/template/{template_name}/vrf/{vrf_name}/l3out/{l3out_name}
Do we need this, or should we put l3Out Dn instead?

2024-12-02 11:16 UTC, closed without merging