[minor_change] Add mso_schema_site_service_graph_node datasource
CiscoDevNet/terraform-provider-mso pull request #171
Opened 2023-02-11 14:04 UTC by lhercot

2023-02-14 15:06 UTC, shrsr commented on mso/datasource_mso_schema_site_service_graph_node.go
> +	stateTemplate := d.Get("template_name").(string)
Is it viable to query all the templates first to check if the template is available or if there is more than one template with the same name? or is this unnecessary?

2023-02-14 15:23 UTC, akinross commented on website/docs/d/mso_schema_site_service_graph_node.html.markdown
> +* `schema_id`          - (Required) Schema ID holding Service Graph.
the Service Graph?

2023-02-14 15:24 UTC, akinross commented on website/docs/d/mso_schema_site_service_graph_node.html.markdown
> +* `template_name`      - (Required) Template Name holding Service Graph.
the Service Graph?

2023-02-14 15:24 UTC, akinross commented on website/docs/d/mso_schema_site_service_graph_node.html.markdown
> +* `service_graph_name` - (Required) Name of Service Graph.
the Service Graph?

2023-02-14 15:24 UTC, akinross commented on website/docs/d/mso_schema_site_service_graph_node.html.markdown
> +* `service_node_type`  - (Required) Type of Service Node to be attached to this Graph.
Type of the Service Node to be attached to the Service Graph?

2023-02-14 15:27 UTC, shrsr commented on mso/datasource_mso_schema_site_service_graph_node.go
> +	stateTemplate := d.Get("template_name").(string)
Nvm @akinross pointed me to getTemplateServiceGraphCont that already does it. Resolving this..

2023-02-14 15:37 UTC, shrsr approved these changes
LGTM

2023-02-15 07:10 UTC, sajagana commented on mso/datasource_mso_schema_site_service_graph_node_test.go
> +	name := makeTestVariable(acctest.RandString(5))
Test failed due to "undefined: makeTestVariable"

2023-02-15 07:17 UTC, sajagana requested changes

2023-02-15 07:17 UTC, sajagana commented on mso/datasource_mso_schema_site_service_graph_node_test.go
> +	resource := CreateServiceNodeResource(name)
Test failed due to: undefined: CreateServiceNodeResource

2023-02-15 07:17 UTC, sajagana commented on mso/datasource_mso_schema_site_service_graph_node_test.go
> +	resource := CreateServiceNodeResource(name)
Test failed due to: undefined: CreateServiceNodeResource

2023-02-15 07:17 UTC, sajagana commented on mso/datasource_mso_schema_site_service_graph_node_test.go
> +	resource := CreateServiceNodeResource(name)
Test failed due to: undefined: CreateServiceNodeResource

2023-02-15 07:17 UTC, sajagana commented on mso/datasource_mso_schema_site_service_graph_node_test.go
> +	resource := CreateServiceNodeResource(name)
Test failed due to: undefined: CreateServiceNodeResource

2023-02-15 07:17 UTC, sajagana commented on website/docs/d/mso_schema_site_service_graph_node.html.markdown
> +
Can we add the GUI Information?

2023-02-15 07:17 UTC, sajagana commented on website/docs/d/mso_schema_site_service_graph_node.html.markdown
> +data "mso_schema_site_service_graph_node" "test" {
mso_schema_site_service_graph_node - not added in the provider.go file

2023-03-02 17:11 UTC, anvitha-jain requested changes

2023-03-02 17:11 UTC, anvitha-jain commented on website/docs/d/mso_schema_site_service_graph_node.html.markdown
> +* `site_nodes.node_name`   - (Optional) Name of Site level Service Node/Device Name. This parameter is required when site is attached with the Template.
site_nodes.site_id -> site_id

Add indentation for sublevel arguments

2023-12-21 14:49 UTC, lhercot commented
Closing this PR as we are deprecating mso_schema_site_service_graph_node in preference of mso_schema_site_service_graph resource.

2023-12-21 14:49 UTC, closed without merging