Add mso_rest data source
CiscoDevNet/terraform-provider-mso pull request #184
Opened 2023-04-18 16:23 UTC by danischm

2023-04-18 19:02 UTC, akinross requested changes

2023-04-18 19:21 UTC, akinross approved these changes
LGTM

2023-04-19 10:52 UTC, sajagana requested changes

2023-04-19 10:52 UTC, sajagana commented on mso/datasource_mso_rest.go
> +	log.Printf("[DEBUG] Beginning Read")
```suggestion
	log.Printf("[DEBUG] %s: Beginning Read", d.Get("path").(string))
```

2023-04-19 11:07 UTC, danischm commented on mso/datasource_mso_rest.go
> +	log.Printf("[DEBUG] Beginning Read")
Updated

2023-04-19 11:12 UTC, sajagana approved these changes
LGTM!

2023-04-19 17:23 UTC, lhercot approved these changes
LGTM

2023-04-19 17:23 UTC, merged