Fixed mso_schema read issue during the state file refresh
CiscoDevNet/terraform-provider-mso pull request #200
Opened 2023-05-04 14:16 UTC by sajagana

Note:

Fixed mso_schema read issue during the state file refresh when the object is not present in the MSO/NDO but present in the state file.

2023-05-05 13:09 UTC, shrsr requested changes

2023-05-09 07:11 UTC, sajagana commented on mso/resource_mso_schema.go
> +		if con.S("code").String() == "404" {
1. This issue may be common for other resources.
2. MSO_Schema failure log: `{"code":404,"message":"Item not found"}` when we delete the object manually. Also attached the sample response value of the  MSO/NDO API.

2023-05-19 14:03 UTC, shrsr approved these changes
LGTM

2023-05-19 18:11 UTC, anvitha-jain approved these changes
LGTM

2023-05-24 12:22 UTC, akinross approved these changes
LGTM

2023-05-24 12:22 UTC, lhercot approved these changes
LGTM

2023-05-24 12:23 UTC, merged