Added site_template_contract_service_graph resource and data-source
CiscoDevNet/terraform-provider-mso pull request #248
Opened 2023-11-03 06:10 UTC by sajagana

Note:

Added site_template_contract_service_graph resource and data-source to manage the Site template contract service graph

2023-11-03 08:50 UTC, anvitha-jain submitted a review, later dismissed
LGTM

2023-11-03 09:41 UTC, sajagana commented on mso/resource_mso_site_template_contract_service_graph.go
> +	apiNodeRelationshipList, err := extractNodes(schemaTemplateServiceGraphCont)
Need to remove the variable err when the https://github.com/CiscoDevNet/terraform-provider-mso/pull/244 PR is merged with the master.

2023-11-06 08:03 UTC, akinross requested changes

2023-11-06 09:16 UTC, akinross requested changes

2023-11-06 09:16 UTC, akinross commented on examples/schema_site_template_contract_service_graph/main.tf
> +resource "mso_schema_site_template_contract_service_graph" "example" {
I think you changed it incorrect, where it should be `mso_schema_site_contract_service_graph`

2023-11-06 09:16 UTC, akinross commented on examples/schema_site_template_contract_service_graph/main.tf
> +resource "mso_schema_site_template_contract_service_graph" "example" {
this applies to the entire name change

2023-11-06 10:33 UTC, akinross approved these changes
LGTM

2023-11-06 19:40 UTC, samiib submitted a review, later dismissed
LGTM

2023-11-07 04:19 UTC, lhercot requested changes

2023-11-07 04:19 UTC, lhercot commented on examples/schema_site_contract_service_graph/main.tf
> +data "mso_schema_template_contract" "c1" {
I think we need a full example with the template contract service graph part in as resources
I would also do the service graph part in it too (at both template and site levels) as resources

2023-11-08 09:20 UTC, akinross approved these changes
LGTM

2023-11-08 18:41 UTC, shrsr approved these changes
LGTM

2023-11-17 02:03 UTC, lhercot approved these changes
LGTM

2023-11-17 02:03 UTC, merged