Addition of the attribute 'description' to a few applicable resources
CiscoDevNet/terraform-provider-mso pull request #260
Opened 2023-12-29 13:12 UTC by shrsr

2024-01-03 10:40 UTC, sajagana requested changes
The current changes looks good, the `description` field should be updated in the data source and resource documentation files.

2024-01-10 18:39 UTC, akinross requested changes

2024-01-10 18:39 UTC, akinross commented on vendor/github.com/ciscoecosystem/mso-go-client/models/schema_template_contract_filter.go
> +func NewTemplateContractFilterRelationShip(ops, path, action, priority, desc string, filterRef map[string]interface{}, directives []interface{}) *PatchPayload {
I think this one is missing description attribute in the docs

2024-01-11 07:48 UTC, akinross reviewed
will you update the mso-go-client vendor files also?

2024-01-11 19:44 UTC, akinross submitted a review, later dismissed
LGTM

2024-01-16 07:42 UTC, akinross approved these changes
LGTM

2024-01-16 15:37 UTC, lhercot approved these changes
LGTM

2024-01-16 15:38 UTC, merged