[bug_fix] Fix importing for mso_schema_template_anp_epg_contract to select the contract with the correct type (DCNE-205)
CiscoDevNet/terraform-provider-mso pull request #299
Opened 2024-10-10 07:49 UTC by akinross

fixes #298

2024-10-10 22:16 UTC, anvitha-jain reviewed
Is this a modification in certain version? If I remember, at one point the contract could have both consumer and provider relationship. Did this change in recent version?

2024-10-11 06:10 UTC, akinross commented
> Is this a modification in certain version? If I remember, at one point the contract could have both consumer and provider relationship. Did this change in recent version?

I see when looking at git blame that the relationship_type is already part of the original code from 4 years ago and is also part of the read function. I assumed ( perhaps wrongly ) that since it is already done also in the read function this is missing in import only by mistake. If it was introduced at a later stage in NDO/MSO then I think it is already broken for the read function for a while, and thus the resource should not be working properly in older versions.

I can look up when this is introduced, will look through release notes and get back to you.

2024-10-11 14:46 UTC, shrsr commented
@anvitha-jain Are you referring to the the resource in Terraform ACI that you worked on?
https://github.com/CiscoDevNet/terraform-provider-aci/commit/1466a6d9a9487ad767038bb5d494e77c85f71858

2024-10-11 14:47 UTC, shrsr submitted a review, later dismissed
LGTM

2024-10-11 17:19 UTC, gmicol submitted a review, later dismissed

2024-10-11 17:39 UTC, sajagana approved these changes
LGTM!

2024-10-11 20:56 UTC, lhercot commented
I think we are mixing it up with the template contract resource filterRelationships, filterRelationshipsConsumerToProvider and filterRelationshipsProviderToConsumer attributes which are separate lists.

The only issue that could exist here is that there are other values for relationship_type in the API documentation and we are not listing them all.

2024-10-11 20:57 UTC, lhercot requested changes

2024-10-11 20:57 UTC, lhercot commented on website/docs/r/schema_template_anp_epg_contract.html.markdown
> +terraform import mso_schema_template_anp_epg_contract.contract1 {schema_id}/template/{template_name}/anp/{anp_name}/epg/{epg_name}/contract/{contract_name}/relationship_type/{consumer|provider}
```suggestion
terraform import mso_schema_template_anp_epg_contract.contract1 {schema_id}/template/{template_name}/anp/{anp_name}/epg/{epg_name}/contract/{contract_name}/relationshipType/{consumer|provider}
```

2024-10-14 10:49 UTC, samiib approved these changes
LGTM

2024-10-16 00:44 UTC, anvitha-jain approved these changes
LGTM

2024-10-17 18:05 UTC, shrsr approved these changes
LGTM

2024-10-21 08:50 UTC, sajagana approved these changes
LGTM!

2024-10-24 13:41 UTC, lhercot approved these changes
LGTM

2024-10-24 13:42 UTC, merged