add test file
CiscoDevNet/terraform-provider-mso pull request #30
Opened 2021-06-29 18:23 UTC by shrsr

2022-08-23 16:56 UTC, anvitha-jain requested changes

2022-08-23 16:56 UTC, anvitha-jain commented on mso/resource_mso_schema_template_filter_entry_test.go
> +		tenant_id     = "5fb5fed8520000452a9e8911"
is it possible to replace the tenant_id? (tenant_id = "5fb5fed8520000452a9e8911" --> tenant_id = "tenant1")

2022-10-17 16:52 UTC, anvitha-jain approved these changes
LGTM

2024-03-02 00:37 UTC, samiib requested changes
Just a few variable consistency changes and some merge conflicts to be fixed.

2024-08-14 14:40 UTC, samiib commented
Syncing PR to Jira

2026-04-24 11:38 UTC, akinross commented
resources outdated and or already developed in the repository

2026-04-24 11:38 UTC, closed without merging