Fix import for bd subnets
CiscoDevNet/terraform-provider-mso pull request #305
Opened 2024-10-17 11:17 UTC by juchowan

2024-10-17 11:20 UTC, akinross approved these changes
LGTM

2024-10-18 18:00 UTC, anvitha-jain requested changes

2024-10-18 18:00 UTC, anvitha-jain commented on website/docs/r/schema_template_bd_subnet.html.markdown
> +terraform import mso_schema_template_bd_subnet.bdsub1 {schema_id}/template/{template_name}/bd/{bd_name}/ip/{ip}
shouldn't this be changed at website/docs/r/schema_site_bd_subnet.html.markdown as well?
Also test the changes made to import in terraform-provider-mso/examples/schema_site_bd_subnet

2024-10-23 18:11 UTC, anvitha-jain commented on website/docs/r/schema_template_bd_subnet.html.markdown
> +terraform import mso_schema_template_bd_subnet.bdsub1 {schema_id}/template/{template_name}/bd/{bd_name}/ip/{ip}
I understand the scenario, it looks good. I was just trying to verify the changes.

2024-10-23 18:11 UTC, anvitha-jain approved these changes
LGTM

2024-10-24 01:39 UTC, samiib approved these changes
LGTM

2024-10-28 10:35 UTC, sajagana approved these changes
LGTM!

2024-10-28 20:51 UTC, lhercot approved these changes
LGTM

2024-10-28 20:52 UTC, merged