[minor_change] Add resource and datasource for mso_template
CiscoDevNet/terraform-provider-mso pull request #309
Opened 2024-10-22 10:01 UTC by akinross

2024-11-11 13:41 UTC, sajagana requested changes

2024-11-11 13:41 UTC, sajagana commented on mso/resource_mso_template.go
> +func getListOfStringsFromSchemaList(d *schema.ResourceData, key string) []string {
Can we move it to utils.go?

2024-11-11 13:41 UTC, sajagana commented on mso/resource_mso_template.go
> +func convertToListOfStrings(values []interface{}) []string {
Can we move it to utils.go?

2024-11-11 13:41 UTC, sajagana commented on mso/resource_mso_template.go
> +func duplicatesInList(list []string) []string {
Can we move it to utils.go?

2024-11-11 13:50 UTC, sajagana approved these changes
LGTM!

2024-11-15 16:54 UTC, shrsr submitted a review, later dismissed
LGTM

2024-11-19 18:37 UTC, gmicol approved these changes
LGTM

2024-11-20 14:16 UTC, lhercot requested changes

2024-11-20 18:42 UTC, gmicol submitted a review, later dismissed
LGTM

2024-11-21 17:52 UTC, shrsr submitted a review, later dismissed
LGTM

2024-11-21 18:17 UTC, anvitha-jain approved these changes
LGTM

2024-11-25 10:16 UTC, samiib approved these changes
LGTM
I created DCNE-261 for the CI.

2024-11-25 10:34 UTC, akinross commented
> LGTM I created DCNE-261 for the CI.

perfect thanks!

2024-11-28 08:35 UTC, sajagana approved these changes
LGTM!

2024-12-02 11:14 UTC, lhercot approved these changes
LGTM

2024-12-02 11:14 UTC, merged