Added new resource - Site External EPG
CiscoDevNet/terraform-provider-mso pull request #52
Opened 2021-09-15 02:49 UTC by anvitha-jain

solves #11

2021-09-15 17:04 UTC, shrsr reviewed
Can you use the go linter on this for proper formatting?

2021-09-18 03:31 UTC, lhercot requested changes

2021-09-18 03:31 UTC, lhercot commented on examples/schema_site_external_epg/main.tf
> +  vrf_template_name     = mso_schema_template_vrf.vrf1.template
Can you align those with the other lines or use terraform fmt (https://www.terraform.io/docs/cli/commands/fmt.html) to do it for you.

2021-09-18 03:31 UTC, lhercot commented on examples/schema_site_external_epg/main.tf
> +}
Can you open an enhancement to keep track of the site L3Out?

2021-09-18 03:31 UTC, lhercot commented on examples/schema_site_external_epg/main.tf
> +}
Same formatting issue as previous one.

2021-09-18 03:31 UTC, lhercot commented on mso/resource_mso_schema_site_external_epg.go
> +// GET and loop through all the schemas and check if you schema is present ("api/v1/schemas/list-identity")
you schema -> the schema

2021-09-18 03:31 UTC, lhercot commented on mso/resource_mso_schema_site_external_epg.go
> +// GET and loop through all the templates in your schema and check if your template is present
your schema -> the schema
your template  -> the template

2021-09-20 16:52 UTC, lhercot approved these changes
LGTM

2021-09-20 16:54 UTC, merged