addition of attributes
CiscoDevNet/terraform-provider-mso pull request #99
Opened 2022-02-04 17:36 UTC by shrsr

2022-02-08 14:33 UTC, lhercot requested changes

2022-02-08 14:33 UTC, lhercot commented on mso/resource_mso_schema_template_bd.go
> +					"encap-flood",
encap_flood

2022-02-08 14:33 UTC, lhercot commented on mso/resource_mso_schema_template_bd.go
> +
Why adding an empty line?

2022-02-08 14:33 UTC, lhercot commented on mso/resource_mso_schema_template_bd.go
> +
Remove empty line

2022-02-08 14:33 UTC, lhercot commented on website/docs/r/schema_template_bd.html.markdown
> +* `unicast_routing` - (Optional) Unicast Routing. Default to false.
Unicast Routing status

2022-02-08 14:33 UTC, lhercot commented on website/docs/r/schema_template_bd.html.markdown
> +* `arp_flooding` - (Optional) ARP Flooding. Default to false.
ARP Flooding status

2022-02-08 14:33 UTC, lhercot commented on website/docs/r/schema_template_bd.html.markdown
> +* `unknown_multicast_flooding` - (Optional) Unknown Multicast Flooding. Allowed values are `flood` and `optimized_flooding`. Default to `flood`.
Unknown Multicast Flooding behavior.

2022-02-09 18:08 UTC, shrsr commented on mso/resource_mso_schema_template_bd.go
> +					"encap-flood",
changed to flood_in_encap

2022-02-10 18:42 UTC, merged